name: CI/CD with terraform
on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_ID}}
  SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}
  SSH_KEY_PUBLIC: ${{ secrets.SSH_KEY_PUBLIC }}
  TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
  AWS_REGION: us-east-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      SERVER_PUBLIC_IP: ${{ steps.pub_ip.outputs.SERVER_PUBLIC_IP}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"
          terraform_wrapper: false

      - name: Verify Terraform installation
        run: terraform --version 

      - name: Terraform init 
        id: init
        run: terraform init -backend-config="bucket=$engys-bucket" -backend-config="region=us-east-1"
        working-directory: ./terraform

      - name: Terraform plan 
        id: plan
        run: |-
          terraform plan \
          -var="region=us-east-1" \
          -var="public_key=$SSH_KEY_PUBLIC" \
          -var="private_key=$SSH_KEY_PRIVATE" \
          -var="key_name=deployer-key" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform apply
        id: apply 
        run: terraform apply PLAN
        working-directory: ./terraform
          
      - name: Debug Terraform Output
        run: terraform output
        working-directory: ./terraform
    
      - name: Set Server Public IP
        id: pub_ip
        run: echo "SERVER_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform
    
      - name: Debug SERVER_PUBLIC_IP
        run: echo "SERVER_PUBLIC_IP=${{ steps.pub_ip.outputs.SERVER_PUBLIC_IP }}"
    

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set IMAGE variable
        run: echo "IMAGE=latest" >> $GITHUB_ENV
      - name: Debug IMAGE
        run: echo "Using IMAGE:$IMAGE"
     

      - name: Debug SERVER_PUBLIC_IP
        run: echo "SERVER_PUBLIC_IP=${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}"


      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-pro1
          IMAGE: latest
        run: |-
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE .
          docker push $REGISTRY/$REPOSITORY:$IMAGE
        working-directory: ./node-app


      - name: Deploy docker image to ec2
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-pro1
          IMAGE: latest
          AWS_DEFAULT_REGION: us-east-1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}
          username: ec2-user            
          key: ${{ env.SSH_KEY_PRIVATE }}
          envs: SSH_KEY_PRIVATE,REGISTRY,REPOSITORY,IMAGE,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION 
          script: |-
            sudo yum update -y
            sudo yum install docker -y
            sudo yum install awscli -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin $REGISTRY
            sudo docker stop myappcontainer || true
            sudo docker rm myappcontainer || true
            sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE
            sudo docker run -d --name myappcontainer -p 80:8080 $REGISTRY/$REPOSITORY:$IMAGE