name: CI/CD with terraform
on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
  SSH_KEY_PRIVATE: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  SSH_KEY_PUBLIC: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_REGION: us-east-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform init 
        id: init
        run: Terraform init -backend-config="bucket=$engys-bucket" -backend-config="region=us-east-1"
        working-directory: ./terraform
      - name: Terraform plan 
        id: plan
        run: |-
          terraform plan \
          -var="region=us-east-1" \
          -var="public_key=$SSH_KEY_PUBLIC" \
          -var="private_key=$SSH_KEY_PRIVATE" \
          -var="key_name=deployer-key" \
          -out=PLAN
        working-directory: ./terraform
      - name: Terraform apply
        id: apply 
        run: terraform apply PLAN
        working-directory: ./terraform

